# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzSYSu-XDQNEE05LJCXOlRhWke9Ej-CL

# 🎯 Bonus Quest: The Exam Oracle 3000
## 📖 Storytime
Welcome, young **data sorcerer** 🧙‍♂️! Your mission is to forge the *Exam Oracle 3000*, a mystical neural network that peers into the academic abyss to predict whether a student will **Pass** or **Fail** their exams. One misstep in your forward propagation spell, and the oracle will spew nonsense!

---

## ⚙️ The Oracle’s Sacred Blueprint
The Council of AI Elders has decreed the following structure:

- **Input Layer**: 3 neurons (e.g., study hours, attendance %, quiz score).  
- **Hidden Layers**: 1 layer, each with 3–5 neurons (your choice). These are the mystery chambers where exam fates are woven.  
- **Output Layer**: 2 neurons:  
  - Neuron 1: Probability of **Pass**.  
  - Neuron 2: Probability of **Fail**.

### 🔮 Activation Magic
Every neuron must wield the **Sigmoid** function to keep predictions between 0 and 1:
$$
\sigma(z) = \frac{1}{1 + e^{-z}}
$$

Note: You can explore and try different activation functions as well!

---



## 🛠️ Your Task Scroll
1. Write **Python code** (NumPy allowed) for **forward propagation**.  
2. Assign your own **weights and biases** manually, as if you're the god of exam grading (e.g., give "study hours" a higher weight).  
3. Try **2–3 different sets** of weights and biases to see how the oracle shifts its predictions.  
4. For each layer, compute:
   $$
   Z = W \cdot X + b
   $$
   $$
   A = \sigma(Z)
   $$
5. Output two probabilities: one for **Pass**, one for **Fail** (e.g., `[0.90, 0.10]` → 90% Pass chance).

NOTE: First you are supposed to do the forward proporgation by yourself on pen and paper and then code! You can try giving different weights and biases and then decide on one which gives the most accurate results!

---

## 🎮 Play Mode: Test Your Oracle
Test your oracle with **2–3 student profiles**:
- **Student A**: [8 study hours, 90% attendance, 85% quiz score] → Should lean toward **Pass**.  
- **Student B**: [2 study hours, 30% attendance, 20% quiz score] → Likely **Fail**.  
- **Student C**: A mystery case with mixed values (your choice)!

---

## 🏆 Bonus Fun
- Print dramatic verdicts:  
  - "🔮 The Oracle whispers: 95% chance of Passing. Rejoice, mortal!"  
  - "💀 The Oracle warns: 12% chance of Passing. May the curve be ever in your favor…"  
- Compare your **Oracle v1**, **Oracle v2**, and **Oracle v3** (different weights/biases). Which is the wisest?

---

## 📜 Rules of the Quest
- **Forward propagation only** (no backpropagation spells).  
- Use **NumPy only**—no TensorFlow, PyTorch, or Keras.  
- Keep it **fun**, **experiment**, and craft the most *realistic* oracle!

---

**Ready to cast your spell?** Build your Exam Oracle 3000! ✨
"""

# Exam Oracle 3000 - Forward Propagation Skeleton (1 Hidden Layer)

import numpy as np

# 1. Define sigmoid activation (In case you have tried different activation function code that here instead of sigmoid)
def sigmoid(z):
    return 1/(1+np.exp(-z))

# 2. Input (Student Profile)
X = np.array([8.0,0.90,0.85])   # Fill with your chosen 3 parameters [e.g. - study_hours, attendance, quiz_score]

# 3. Initialize weights and biases (Set your own weights and biases!)
# Hidden layer
W1 = np.array([[0.5, 0.2, 0.1],
               [0.3, 0.4, 0.3],
               [0.2, 0.1, 0.6]])
b1 = np.array([0.0,0.0,0.0])

# Output layer (2 neurons: Pass, Fail)
W2 = np.array([[0.6, 0.5, 0.4],
               [0.4, 0.5, 0.6]])
b2 = np.array([0.0,0.0])

# 4. Forward Propagation
# Input → Hidden
Z1 =   np.dot(W1, X) + b1
A1 =   sigmoid(Z1)

# Hidden → Output  (Try thinking this on your own)
Z2 =  np.dot(W2, A1) + b2
A2 = sigmoid(Z2)

# 5. Final Prediction
print("Oracle prediction (Pass, Fail):", A2)


#TRY VERIFYING THE RESULTS WITH YOUR WEIGHTS AND BIASES THAT YOU HAVE TRIED ON PEN PAPER!!

"""REFERENCE LINKS:

https://www.youtube.com/watch?v=7MuiScUkboE

https://www.youtube.com/watch?v=sNTtUV9yE_M&t=23s

https://www.youtube.com/watch?v=99CcviQchd8 (For coding)


BONUS: If you are still curious you can always explore more about artificial neural network and code using tensorflow!
"""